{% set data = load_setup_py_data() %}

package:
  name: tetrimmer
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - tetrimmer=tetrimmer.TEtrimmer:main


requirements:
  host:
    - python >=3.8,<3.11
  run:
    - python >=3.8,<3.11
    - perl >=5.26.2,<5.26.3.0a0
    - r-base
    - blast=2.5.0
    - rmblast=2.10.0
    - biopython >=1.81
    - bedtools >=2.31.1
    - cd-hit >=4.8.1
    - dataclasses
    - emboss >=6.5.7
    - hmmer >=3.3.2
    - iqtree >=2.2.5
    - matplotlib >=3.8.1
    - mafft >=7.520
    - multiprocess >=0.70.15
    - numpy >=1.26.0
    - pandas >=2.1.2
    - pfam_scan >=1.6
    - pypdf2 >=2.11.1
    - regex >=2023.10.3
    - repeatmodeler=2.0.1  
    - repeatmasker
    - requests >=2.31.0
    - samtools >=1.18
    - scikit-learn >=1.3.2
    - tk >=8.6.13
    - urllib3 >=2.0.7
    - click >=8.1.7
    - dill >=0.3.7
    - joblib >=1.3.2
    - nseg >=1.0.1
    - recon >=1.08
    - trf >=4.09.1
    - ghostscript

test:
  imports:
    - tetrimmer
    
about:
  home: https://github.com/qjiangzhao/TEtrimmer.git
  license: GPLv3
  summary: "TEtrimmer is designed to replace and assist TE manual curation."

extra:
  recipe-maintainers:
    - qianjiangzhao
